#!/bin/bash
##############################################
########## Author: Jay Lux Ferro #############
##############################################

## params
## $1 = counter
## $2 = scenario

for x in $(seq $1);
do
python $0".py" $x $2
done
