required = ["github.com/mdlayher/raw"]

[[constraint]]
  name = "github.com/evilsocket/islazy"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/bettercap/gatt"

[[constraint]]
  name = "github.com/bettercap/readline"
  version = "1.4.0"

[[constraint]]
  name = "github.com/bettercap/recording"
  revision = "3ce1dcf032e391eb321311b34cdf31c6fc9523f5"

[[constraint]]
  branch = "master"
  name = "github.com/chifflier/nfqueue-go"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/goproxy"

[[constraint]]
  branch = "master"
  name = "github.com/gobwas/glob"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/google/gopacket"
  revision = "v1.1.16"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-vhost"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/go-tld"

[[constraint]]
  name = "github.com/malfunkt/iprange"
  version = "0.9.0"

[[constraint]]
  revision = "480b93709cce56651807d3fdeb260a5a7c4e2d5f"
  name = "github.com/mdlayher/raw"

[[constraint]]
  branch = "master"
  name = "github.com/mdlayher/dhcp6"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  branch = "master"
  name = "github.com/tarm/serial"

[[constraint]]
  name = "github.com/adrianmo/go-nmea"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
